version: '3.8'

services:
  flower-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flower-server
    ports:
      - "8080:8080"
    networks:
      - flower-network

networks:
  flower-network:
    external: true